### ISSUE TITLE
help

### ISSUE THREAD

**Issue by tjujingzong** [ShiYu-TJ/OpenGL-animation_TJU-Final-assignment#1]
调试运行时会出现如下错误，请问学长该如何解决呢
![image](https://user-images.githubusercontent.com/88825933/198926548-fcfb3245-5fb0-49a8-bea1-670e6f4bf22e.png)

**Comment by ShiYu-TJ** [comment]
我忘记了，当时没有记录就是这样子，不过这应该是链接出问题了，我补充一个配置文件吧，把我的配置传到github。
希望管用，如果不管用也没办法了……
应该会在下午两点前弄完，到时候可以看一下，我先吃饭去了。

**Comment by tjujingzong** [comment]
感谢学长回复，这个问题我刚刚解决了，参考了下面这篇博客。
https://blog.csdn.net/LHXvs2015/article/details/120674525
